// This class holds static references to keys used for storing data in shared preferences.
class SharedPrefConstants {
  static const String languageCode = 'languageCode';
  static const String countryCode = 'countryCode';
  static const String expiresIn = 'expires_in';
  static const String refreshExpiresIn = 'refresh_expires_in';

  static const String portOfSubmission = 'setPortofSubmission';
  static const String orgName = 'orgName';
  static const String orgNameArabic = 'orgNameArabic';
  static const String agencyCode = 'agencyCode';
  static const String agency = 'agency';
  static const String portCode = 'portCode';
  static const String portId = 'portId';
  static const String appId = 'appId';
  static const String userType = 'userType';
  static const String stakeHolder = 'stakeHolder';
  static const String employeeName = 'employeeName';
  static const String demoToken =
      'eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI5a2NNcmlHSzRBbFNRZUwzbUZSbld5ODJFcU5rdDcxdE8xMHpXUnhRR0VrIn0.eyJleHAiOjE3MzEzOTM2NzYsImlhdCI6MTczMTM5MzM3NiwiYXV0aF90aW1lIjoxNzMxMzkwODkxLCJqdGkiOiJlMWIwOTNkYi0yZGRkLTRkMDQtYWI2YS0yZjI4MTBiZTE5ZTAiLCJpc3MiOiJodHRwczovL3EtcGNzLnRhYmFkdWwuc2EvYXV0aC9yZWFsbXMvUENTIiwiYXVkIjpbInJlYWxtLW1hbmFnZW1lbnQiLCJhY2NvdW50Il0sInN1YiI6IjNmNjE5YWQ0LWJjZjItNGE0Ny1iNTYxLWY4N2RjNjI3MDg4YiIsInR5cCI6IkJlYXJlciIsImF6cCI6IlBDU19jbGllbnQiLCJub25jZSI6IjViODk2NGM0LThkZGItNGI0Yy05ODA3LTVkYzIyYjI2MmRmNiIsInNlc3Npb25fc3RhdGUiOiIzYjQ1YTYzZi1kNDdiLTQwNjUtODEyZS0yY2YxNmZmNzc2ZTIiLCJhbGxvd2VkLW9yaWdpbnMiOlsiaHR0cHM6Ly9xLXBjcy50YWJhZHVsLnNhIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIiwicGNzdXNlciIsIlNBIiwiZGVmYXVsdC1yb2xlcy1wY3MiXX0sInJlc291cmNlX2FjY2VzcyI6eyJyZWFsbS1tYW5hZ2VtZW50Ijp7InJvbGVzIjpbInZpZXctcmVhbG0iLCJ2aWV3LWlkZW50aXR5LXByb3ZpZGVycyIsIm1hbmFnZS1pZGVudGl0eS1wcm92aWRlcnMiLCJpbXBlcnNvbmF0aW9uIiwicmVhbG0tYWRtaW4iLCJjcmVhdGUtY2xpZW50IiwibWFuYWdlLXVzZXJzIiwicXVlcnktcmVhbG1zIiwidmlldy1hdXRob3JpemF0aW9uIiwicXVlcnktY2xpZW50cyIsInF1ZXJ5LXVzZXJzIiwibWFuYWdlLWV2ZW50cyIsIm1hbmFnZS1yZWFsbSIsInZpZXctZXZlbnRzIiwidmlldy11c2VycyIsInZpZXctY2xpZW50cyIsIm1hbmFnZS1hdXRob3JpemF0aW9uIiwibWFuYWdlLWNsaWVudHMiLCJxdWVyeS1ncm91cHMiXX0sImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoib3BlbmlkIHBjc3VzZXIgZW1haWwgcHJvZmlsZSIsInNpZCI6IjNiNDVhNjNmLWQ0N2ItNDA2NS04MTJlLTJjZjE2ZmY3NzZlMiIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwibmFtZSI6IkFEQU0gWWFzc2VpbiIsInByZWZlcnJlZF91c2VybmFtZSI6ImMwOTA3IiwiZ2l2ZW5fbmFtZSI6IkFEQU0iLCJmYW1pbHlfbmFtZSI6Illhc3NlaW4iLCJlbWFpbCI6ImpnaGFmZWVzQHRhYmFkdWwuc2EifQ.FfYANPL8n21z6Df9IIymwIWelQtGtFgUdW-iRsqHZSTWq9CUnKKTF1BXAVlvUUhJe7ildTDPUgZF7OhhbHR30LzvNloYatFQpJV-PNm2PQJBRfEh307_xQaIX4UOL22_vTgPR5xJE_ZIBmNlC2LoQpzNJBs1G_cees_3Jn6wtIWSI0p4xKelhlO4veC2MrhIXLTqPw2M7IfNK2linS0grhW1saf6-oZm5M8IR9BCOglqBg1LCpA-JNMf5BNIyUcLLAY0pcyC__G4n6Z9zbJV2qLGJd5upveSdYmwIg1Y2MzXl5QlczFF3Nm3nQuRlvgQo7-KQ2BxlLlsVCH2_-UZ-w';
  static const String localizationData = 'LocalizationData';
  static const String useBiometric = 'useBiometric';
  static const String userData = 'userData';
  static const String permissionList = "permissionList";

}
