// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMm64KQnsePD5EBqynolizSGV2jEB06ag',
    appId: '1:416382625901:web:04c1c33c5c0b7ccbd23764',
    messagingSenderId: '416382625901',
    projectId: 'classify-26e2c',
    authDomain: 'classify-26e2c.firebaseapp.com',
    storageBucket: 'classify-26e2c.firebasestorage.app',
    measurementId: 'G-BBFNZQCQ36',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaRd3ORkZqh8-gBryB80LqHr0WUMQRwi8',
    appId: '1:416382625901:android:6bada4e7ccf0ae70d23764',
    messagingSenderId: '416382625901',
    projectId: 'classify-26e2c',
    storageBucket: 'classify-26e2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEJBwTvlx8URvoKT9hi64RDoLHnTshQeM',
    appId: '1:416382625901:ios:6fa813f25046eb13d23764',
    messagingSenderId: '416382625901',
    projectId: 'classify-26e2c',
    storageBucket: 'classify-26e2c.firebasestorage.app',
    androidClientId: '416382625901-4go9r5idog1l1rl0935kcb10ndubifto.apps.googleusercontent.com',
    iosClientId: '416382625901-ohi8v9pjci9batpbs4ino4r0k0krj613.apps.googleusercontent.com',
    iosBundleId: 'com.maizer.flutterCore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEJBwTvlx8URvoKT9hi64RDoLHnTshQeM',
    appId: '1:416382625901:ios:43cb2f552582efddd23764',
    messagingSenderId: '416382625901',
    projectId: 'classify-26e2c',
    storageBucket: 'classify-26e2c.firebasestorage.app',
    androidClientId: '416382625901-4go9r5idog1l1rl0935kcb10ndubifto.apps.googleusercontent.com',
    iosClientId: '416382625901-gc0fa5suqmg4hvl862vm3n4egroj9edo.apps.googleusercontent.com',
    iosBundleId: 'com.example.freeLancerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMm64KQnsePD5EBqynolizSGV2jEB06ag',
    appId: '1:416382625901:web:a90124c47aad3257d23764',
    messagingSenderId: '416382625901',
    projectId: 'classify-26e2c',
    authDomain: 'classify-26e2c.firebaseapp.com',
    storageBucket: 'classify-26e2c.firebasestorage.app',
    measurementId: 'G-S9FMWNSNWG',
  );
}
